services:
  ech0:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6277"
    volumes:
      - ./data:/app/data
      - ./backup:/app/backup
    environment:
      - JWT_SECRET=${JWT_SECRET}
    image: sn0wl1n/ech0:v3.0.5
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
