services:
  pg-exporter:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9187"
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
    image: prometheuscommunity/postgres-exporter:v0.19.0
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
