services:
  db:
    container_name: ${CONTAINER_NAME}_db
    image: postgres:18-alpine
    restart: always
    networks:
      - 1panel-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    labels:
      createdBy: "Apps"

  redis:
    container_name: ${CONTAINER_NAME}_redis
    image: redis:7-alpine
    restart: always
    networks:
      - 1panel-network
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
    labels:
      createdBy: "Apps"

  afilmory:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/afilmory/afilmory-core:latest
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1841"
    environment:
      NODE_ENV: production
      HOSTNAME: '0.0.0.0'
      PORT: '1841'
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_NAME}_db:5432/${POSTGRES_DB}'
      REDIS_URL: 'redis://${CONTAINER_NAME}_redis:6379/0'
      CONFIG_ENCRYPTION_KEY: ${CONFIG_ENCRYPTION_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
