services:
  afilmory:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/afilmory/afilmory-core:latest
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:1841"
    environment:
      NODE_ENV: production
      HOSTNAME: '0.0.0.0'
      PORT: '1841'
      DATABASE_URL: 'postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}'
      REDIS_URL: 'redis://:${PANEL_REDIS_ROOT_PASSWORD}@${PANEL_REDIS_HOST}:6379/0'
      CONFIG_ENCRYPTION_KEY: ${CONFIG_ENCRYPTION_KEY}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
