services:
  imgproxy:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
    image: darthsim/imgproxy:v3.30.1
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
